USE [master]
GO

/****** Object:  Database [FMBQuickBooks]    Script Date: 9/5/2018 4:01:40 PM ******/
CREATE DATABASE [FMBQuickBooks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FMBQuickBooks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FMBQuickBooks.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FMBQuickBooks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FMBQuickBooks_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FMBQuickBooks] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FMBQuickBooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FMBQuickBooks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET ARITHABORT OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FMBQuickBooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FMBQuickBooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FMBQuickBooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FMBQuickBooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET RECOVERY FULL 
GO

ALTER DATABASE [FMBQuickBooks] SET  MULTI_USER 
GO

ALTER DATABASE [FMBQuickBooks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FMBQuickBooks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FMBQuickBooks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FMBQuickBooks] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FMBQuickBooks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FMBQuickBooks] SET  READ_WRITE 
GO


