USE [master]
GO

/****** Object:  Database [FMBDataHub]    Script Date: 8/28/2018 10:31:55 AM ******/
CREATE DATABASE [FMBDataHub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FMBDataHub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FMBDataHub.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FMBDataHub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FMBDataHub_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FMBDataHub] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FMBDataHub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FMBDataHub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FMBDataHub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FMBDataHub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FMBDataHub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FMBDataHub] SET ARITHABORT OFF 
GO

ALTER DATABASE [FMBDataHub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FMBDataHub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FMBDataHub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FMBDataHub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FMBDataHub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FMBDataHub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FMBDataHub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FMBDataHub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FMBDataHub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FMBDataHub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FMBDataHub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FMBDataHub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FMBDataHub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FMBDataHub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FMBDataHub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FMBDataHub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FMBDataHub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FMBDataHub] SET RECOVERY FULL 
GO

ALTER DATABASE [FMBDataHub] SET  MULTI_USER 
GO

ALTER DATABASE [FMBDataHub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FMBDataHub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FMBDataHub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FMBDataHub] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FMBDataHub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FMBDataHub] SET  READ_WRITE 
GO


